// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/bookshop.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookShopClient is the client API for BookShop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookShopClient interface {
	GetBookList(ctx context.Context, in *GetBookListRequest, opts ...grpc.CallOption) (*GetBookListResponse, error)
}

type bookShopClient struct {
	cc grpc.ClientConnInterface
}

func NewBookShopClient(cc grpc.ClientConnInterface) BookShopClient {
	return &bookShopClient{cc}
}

func (c *bookShopClient) GetBookList(ctx context.Context, in *GetBookListRequest, opts ...grpc.CallOption) (*GetBookListResponse, error) {
	out := new(GetBookListResponse)
	err := c.cc.Invoke(ctx, "/BookShop/GetBookList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookShopServer is the server API for BookShop service.
// All implementations must embed UnimplementedBookShopServer
// for forward compatibility
type BookShopServer interface {
	GetBookList(context.Context, *GetBookListRequest) (*GetBookListResponse, error)
	mustEmbedUnimplementedBookShopServer()
}

// UnimplementedBookShopServer must be embedded to have forward compatible implementations.
type UnimplementedBookShopServer struct {
}

func (UnimplementedBookShopServer) GetBookList(context.Context, *GetBookListRequest) (*GetBookListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookList not implemented")
}
func (UnimplementedBookShopServer) mustEmbedUnimplementedBookShopServer() {}

// UnsafeBookShopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookShopServer will
// result in compilation errors.
type UnsafeBookShopServer interface {
	mustEmbedUnimplementedBookShopServer()
}

func RegisterBookShopServer(s grpc.ServiceRegistrar, srv BookShopServer) {
	s.RegisterService(&BookShop_ServiceDesc, srv)
}

func _BookShop_GetBookList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookShopServer).GetBookList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BookShop/GetBookList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookShopServer).GetBookList(ctx, req.(*GetBookListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookShop_ServiceDesc is the grpc.ServiceDesc for BookShop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookShop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BookShop",
	HandlerType: (*BookShopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookList",
			Handler:    _BookShop_GetBookList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bookshop.proto",
}
